spring:
  r2dbc:
    protocol: r2dbc:postgresql
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: postgres

  sql:
    init:
      mode: always
      continue-on-error: false

  logging:
    config: classpath:logback-local.xml

app:
  security:
    jwt:
      secret: 67f2eca07f6d95526b60e9421dc040e20d239a4c0d6f545135e699178f5b8313
      expiration: 28800
    password:
      hash:
        rounds: 30

  storage:
    cred-path: src/main/resources/key.json
    project-id: terry-dev
    bucket-name: terry-storage-dev