-- [CREATE] tables
CREATE TABLE IF NOT EXISTS IMAGES (
    id SERIAL NOT NULL,
    url TEXT NOT NULL,
    width INT,
    height INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    age BIGINT,
    profileImgId SERIAL,
    PRIMARY KEY (id),
    FOREIGN KEY (profileImgId) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS POSTINGS (
    id SERIAL NOT NULL,
    userId SERIAL NOT NULL,
    contents TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- comment table
CREATE TABLE IF NOT EXISTS POSTING_COMMENTS (
    id SERIAL NOT NULL,
    userId SERIAL NOT NULL,
    postingId SERIAL NOT NULL,
    contents TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (postingId) REFERENCES postings(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS POSTING_IMAGES (
    id SERIAL NOT NULL,
    imageId SERIAL NOT NULL,
    postingId SERIAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (imageId) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (postingId) REFERENCES postings(id) ON DELETE CASCADE ON UPDATE CASCADE
);