-- [CREATE] tables
CREATE TABLE IF NOT EXISTS IMAGES (
    image_id SERIAL NOT NULL,
    url TEXT NOT NULL,
    width INT,
    height INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (image_id)
);

CREATE TABLE IF NOT EXISTS USERS (
    user_id SERIAL NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    age BIGINT,
    profile_img_id SERIAL,
    PRIMARY KEY (user_id),
    FOREIGN KEY (profile_img_id) REFERENCES images(image_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS POSTINGS (
    posting_id SERIAL NOT NULL,
    user_id SERIAL NOT NULL,
    contents TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(posting_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- comment table
CREATE TABLE IF NOT EXISTS POSTING_COMMENTS (
    comment_id SERIAL NOT NULL,
    user_id SERIAL NOT NULL,
    posting_id SERIAL NOT NULL,
    contents TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(comment_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (posting_id) REFERENCES postings(posting_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS POSTING_IMAGES (
    posting_image_id SERIAL NOT NULL,
    image_id SERIAL NOT NULL,
    posting_id SERIAL NOT NULL,
    PRIMARY KEY(posting_image_id),
    FOREIGN KEY (image_id) REFERENCES images(image_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (posting_id) REFERENCES postings(posting_id) ON DELETE CASCADE ON UPDATE CASCADE
);